<a href="https://colab.research.google.com/github/sabanoureen/10pearlsAQI/blob/main/pandas_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("/content/pokemon_data.csv")
df
#df_xlsx=pd.read_excel("/content/pokemon_data.xlsx")
#df_xlsx.head()
#df_txt=pd.read_csv("/content/pokemon_data.txt",delimiter='\t') #txt file
#df_txt.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [3]:
# Reading data
df.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [4]:
print(df['Name'][0:5])

0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
Name: Name, dtype: object

In [5]:
print(df[['Name','Type 1','HP']])  # 3 different col

                      Name   Type 1  HP
0                Bulbasaur    Grass  45
1                  Ivysaur    Grass  60
2                 Venusaur    Grass  80
3    VenusaurMega Venusaur    Grass  80
4               Charmander     Fire  39
..                     ...      ...  ..
795                Diancie     Rock  50
796    DiancieMega Diancie     Rock  50
797    HoopaHoopa Confined  Psychic  80
798     HoopaHoopa Unbound  Psychic  80
799              Volcanion     Fire  80

[800 rows x 3 columns]

In [6]:
print(df.iloc[1:5])  # find 1 to 4 rows

   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
1  2                Ivysaur  Grass  Poison  60      62       63       80
2  3               Venusaur  Grass  Poison  80      82       83      100
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122
4  4             Charmander   Fire     NaN  39      52       43       60

   Sp. Def  Speed  Generation  Legendary
1       80     60           1      False
2      100     80           1      False
3      120     80           1      False
4       50     65           1      False

In [7]:
print(df.iloc[4,2])                      #iloc =         #[row index,col index]
# use iloc to find location

Fire

In [8]:
#for index,row in df.iterrows():  # Find iterate though all rows
#  print(index,row)

In [9]:
# loc :find specifc information ,mostly text based
df.loc[4,'Name']                           #loc =             #[row index,col name]

'Charmander'

In [10]:
df.loc[:,['Name','HP']]   # give me all rows of these 2 colms

                      Name  HP
0                Bulbasaur  45
1                  Ivysaur  60
2                 Venusaur  80
3    VenusaurMega Venusaur  80
4               Charmander  39
..                     ...  ..
795                Diancie  50
796    DiancieMega Diancie  50
797    HoopaHoopa Confined  80
798     HoopaHoopa Unbound  80
799              Volcanion  80

[800 rows x 2 columns]

In [11]:
df.loc[1:3,'Sp. Def']

1     80
2    100
3    120
Name: Sp. Def, dtype: int64

In [12]:
df.loc[df['Type 1']=="Grass"]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
48,43,Oddish,Grass,Poison,45,50,55,75,65,30,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
718,650,Chespin,Grass,NaN,56,61,65,48,45,38,6,False
719,651,Quilladin,Grass,NaN,61,78,95,56,58,57,6,False
720,652,Chesnaught,Grass,Fighting,88,107,122,74,75,64,6,False
740,672,Skiddo,Grass,NaN,66,65,48,62,57,52,6,False
741,673,Gogoat,Grass,NaN,123,100,62,97,81,68,6,False

In [13]:
# Sorting / Describing Data:

In [14]:
df.sort_values(['Name','HP'], ascending=True) # sort in ascending

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True

In [15]:
# making changes to the data :
df.head(2)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False

In [16]:
df['Total']=df['HP']+df['Attack']+df['Defense']+df['Sp. Atk']+df['Sp. Def']+df['Speed']
df.head(2)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405

In [17]:
df=df.drop(columns=['Total'])   # drop column=Total
df.head(2)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False

In [18]:
df['Total']=df.iloc[:,4:10].sum(axis=1)
cols=list(df.columns)
df=df[cols[0:4]+[cols[-1]]+cols[4:12]]
df.head(2)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False

In [19]:
df.head(2)
df.to_csv('modified.csv',index=False)

In [20]:
# Filtering Data:

In [21]:
new_df=df.loc[(df['Type 1']=='Grass') & (df['Type 2']=='Poison') & (df['HP']>70)]
new_df.to_csv("data_filter.csv")

In [22]:
df.loc[df['Name'].str.contains("Mega")] # include 'Mega
#df.loc[~df['Name'].str.contains("Mega")] # not include 'Mega

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,579,83,80,80,135,80,121,1,False
71,65,AlakazamMega Alakazam,Psychic,NaN,590,55,50,65,175,95,150,1,False
87,80,SlowbroMega Slowbro,Water,Psychic,590,95,75,180,130,80,30,1,False
102,94,GengarMega Gengar,Ghost,Poison,600,60,65,80,170,95,130,1,False
124,115,KangaskhanMega Kangaskhan,Normal,NaN,590,105,125,100,60,100,100,1,False
137,127,PinsirMega Pinsir,Bug,Flying,600,65,155,120,65,90,105,1,False
141,130,GyaradosMega Gyarados,Water,Dark,640,95,155,109,70,130,81,1,False
154,142,AerodactylMega Aerodactyl,Rock,Flying,615,80,135,85,70,95,150,1,False
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,True
164,150,MewtwoMega Mewtwo Y,Psychic,NaN,780,106,150,70,194,120,140,1,True
168,154,Meganium,Grass,NaN,525,80,82,100,83,100,80,2,False
196,181,AmpharosMega Ampharos,Electric,Dragon,610,90,95,105,165,110,45,2,False
224,208,SteelixMega Steelix,Steel,Ground,610,75,125,230,55,95,30,2,False
229,212,ScizorMega Scizor,Bug,Steel,600,70,150,140,65,100,75,2,False
232,214,HeracrossMega Heracross,Bug,Fighting,600,80,185,115,40,105,75,2,False
248,229,HoundoomMega Houndoom,Dark,Fire,600,75,90,90,140,90,115,2,False
268,248,TyranitarMega Tyranitar,Rock,Dark,700,100,164,150,95,120,71,2,False
275,254,SceptileMega Sceptile,Grass,Dragon,630,70,110,75,145,85,145,3,False
279,257,BlazikenMega Blaziken,Fire,Fighting,630,80,160,80,130,80,100,3,False
283,260,SwampertMega Swampert,Water,Ground,635,100,150,110,95,110,70,3,False
306,282,GardevoirMega Gardevoir,Psychic,Fairy,618,68,85,65,165,135,100,3,False
327,302,SableyeMega Sableye,Dark,Ghost,480,50,85,125,85,115,20,3,False
329,303,MawileMega Mawile,Steel,Fairy,480,50,105,125,55,95,50,3,False
333,306,AggronMega Aggron,Steel,NaN,630,70,140,230,60,80,50,3,False
336,308,MedichamMega Medicham,Fighting,Psychic,510,60,100,85,80,85,100,3,False
339,310,ManectricMega Manectric,Electric,NaN,575,70,75,80,135,80,135,3,False
349,319,SharpedoMega Sharpedo,Water,Dark,560,70,140,70,110,65,105,3,False
354,323,CameruptMega Camerupt,Fire,Ground,560,70,120,100,145,105,20,3,False
366,334,AltariaMega Altaria,Dragon,Fairy,590,75,110,110,110,105,80,3,False
387,354,BanetteMega Banette,Ghost,NaN,555,64,165,75,93,83,75,3,False
393,359,AbsolMega Absol,Dark,NaN,565,65,150,60,115,60,115,3,False
397,362,GlalieMega Glalie,Ice,NaN,580,80,120,80,120,80,100,3,False
409,373,SalamenceMega Salamence,Dragon,Flying,700,95,145,130,120,90,120,3,False
413,376,MetagrossMega Metagross,Steel,Psychic,700,80,145,150,105,110,110,3,False
418,380,LatiasMega Latias,Dragon,Psychic,700,80,100,120,140,150,110,3,True
420,381,LatiosMega Latios,Dragon,Psychic,700,80,130,100,160,120,110,3,True
426,384,RayquazaMega Rayquaza,Dragon,Flying,780,105,180,100,180,100,115,3,True
476,428,LopunnyMega Lopunny,Normal,Fighting,580,65,136,94,54,96,135,4,False
494,445,GarchompMega Garchomp,Dragon,Ground,700,108,170,115,120,95,92,4,False
498,448,LucarioMega Lucario,Fighting,Steel,625,70,145,88,140,70,112,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,594,90,132,105,132,105,30,4,False
527,475,GalladeMega Gallade,Psychic,Fighting,618,68,165,95,65,115,110,4,False
591,531,AudinoMega Audino,Normal,Fairy,545,103,60,126,80,126,50,5,False
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True

In [23]:
import re
df.loc[df['Name'].str.contains('pi[a-z]*',flags=re.I,regex=True)]  #it finds letter contains pi
#df.loc[df['Name'].str.contains('^pi[a-z]*',flags=re.I,regex=True)]  #it finds letter contains pi

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
13,10,Caterpie,Bug,NaN,195,45,30,35,20,20,45,1,False
20,16,Pidgey,Normal,Flying,251,40,45,40,35,35,56,1,False
21,17,Pidgeotto,Normal,Flying,349,63,60,55,50,50,71,1,False
22,18,Pidgeot,Normal,Flying,479,83,80,75,70,70,101,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,579,83,80,80,135,80,121,1,False
30,25,Pikachu,Electric,NaN,320,35,55,40,50,50,90,1,False
42,37,Vulpix,Fire,NaN,299,38,41,40,50,65,65,1,False
76,70,Weepinbell,Grass,Poison,390,65,90,50,85,45,55,1,False
84,78,Rapidash,Fire,NaN,500,65,100,70,80,80,105,1,False
136,127,Pinsir,Bug,NaN,500,65,125,100,55,70,85,1,False
137,127,PinsirMega Pinsir,Bug,Flying,600,65,155,120,65,90,105,1,False
181,167,Spinarak,Bug,Poison,250,40,60,40,40,40,30,2,False
186,172,Pichu,Electric,NaN,205,20,40,15,35,35,60,2,False
189,175,Togepi,Fairy,NaN,245,35,20,65,40,65,20,2,False
202,187,Hoppip,Grass,Flying,250,35,35,40,35,55,50,2,False
219,204,Pineco,Bug,NaN,290,50,65,90,35,35,15,2,False
239,221,Piloswine,Ice,Ground,450,100,100,80,60,60,50,2,False
266,247,Pupitar,Rock,Ground,410,70,84,70,65,70,51,2,False
345,316,Gulpin,Poison,NaN,302,70,43,53,43,53,40,3,False
357,326,Grumpig,Psychic,NaN,470,80,45,65,90,110,80,3,False
358,327,Spinda,Normal,NaN,360,60,60,60,60,60,60,3,False
359,328,Trapinch,Ground,NaN,290,45,100,45,45,45,10,3,False
390,357,Tropius,Grass,Flying,460,99,68,83,72,87,51,3,False
438,393,Piplup,Water,NaN,314,53,51,53,61,56,40,4,False
463,416,Vespiquen,Bug,Flying,474,70,80,102,80,102,40,4,False
488,440,Happiny,Normal,NaN,220,100,5,5,15,65,30,4,False
490,442,Spiritomb,Ghost,Dark,485,50,92,108,92,108,35,4,False
501,451,Skorupi,Poison,Bug,330,40,50,90,30,55,65,4,False
502,452,Drapion,Poison,Dark,500,70,90,110,60,75,95,4,False
557,498,Tepig,Fire,NaN,308,65,63,45,45,45,45,5,False
558,499,Pignite,Fire,Fighting,418,90,93,55,70,55,55,5,False
578,519,Pidove,Normal,Flying,264,50,55,50,36,30,43,5,False
596,536,Palpitoad,Water,Ground,384,75,65,55,65,55,69,5,False
716,648,MeloettaPirouette Forme,Normal,Fighting,600,100,128,90,77,77,128,5,False
718,650,Chespin,Grass,NaN,313,56,61,65,48,45,38,6,False

In [24]:
# conditional changes:

In [25]:
df.loc[df['Type 1']=="Fire",'Legendary']=True
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [26]:
# conditional Changes

In [27]:
df.loc[df['Total']>500,['Generation','Legendary']]=['Test 1','Test 2']
df

/tmp/ipykernel_6741/3855931756.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Test 1' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[df['Total']>500,['Generation','Legendary']]=['Test 1','Test 2']
/tmp/ipykernel_6741/3855931756.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Test 2' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df.loc[df['Total']>500,['Generation','Legendary']]=['Test 1','Test 2']

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,Test 1,Test 2
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,Test 1,Test 2
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,Test 1,Test 2
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,Test 1,Test 2
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,Test 1,Test 2
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,Test 1,Test 2
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,Test 1,Test 2

In [28]:
# Aggregate statistics/ group by

In [29]:
df=pd.read_csv('modified.csv')
df.head(3)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False

In [30]:
df=pd.read_csv('modified.csv')
df.groupby('Type 1')[['HP', 'Attack', 'Defense']].mean()

                 HP      Attack     Defense
Type 1
Bug       56.884058   70.971014   70.724638
Dark      66.806452   88.387097   70.225806
Dragon    83.312500  112.125000   86.375000
Electric  59.795455   69.090909   66.295455
Fairy     74.117647   61.529412   65.705882
Fighting  69.851852   96.777778   65.925926
Fire      69.903846   84.769231   67.769231
Flying    70.750000   78.750000   66.250000
Ghost     64.437500   73.781250   81.187500
Grass     67.271429   73.214286   70.800000
Ground    73.781250   95.750000   84.843750
Ice       72.000000   72.750000   71.416667
Normal    77.275510   73.469388   59.846939
Poison    67.250000   74.678571   68.821429
Psychic   70.631579   71.456140   67.684211
Rock      65.363636   92.863636  100.795455
Steel     65.222222   92.703704  126.370370
Water     72.062500   74.151786   72.946429

In [31]:
df.groupby('Type 1').mean(numeric_only=True).sort_values('Attack', ascending=False)

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,,
Dragon,474.375000,550.531250,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250,3.875000,0.375000
Fighting,363.851852,416.444444,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074,3.370370,0.000000
Ground,356.281250,437.500000,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250,3.156250,0.125000
Rock,392.727273,453.750000,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091,3.454545,0.090909
Steel,442.851852,487.703704,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259,3.851852,0.148148
Dark,461.354839,445.741935,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290,4.032258,0.064516
Fire,327.403846,458.076923,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308,3.211538,0.096154
Flying,677.750000,485.000000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000,5.500000,0.500000
Poison,251.785714,399.142857,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429,2.535714,0.000000
Water,303.089286,430.455357,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286,2.857143,0.035714
Ghost,486.500000,439.562500,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750,4.187500,0.062500
Normal,319.173469,401.683673,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020,3.051020,0.020408
Grass,344.871429,421.142857,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571,3.357143,0.042857
Ice,423.541667,433.458333,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333,3.541667,0.083333
Psychic,380.807018,475.947368,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228,3.385965,0.245614
Bug,334.492754,378.927536,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159,3.217391,0.000000
Electric,363.500000,443.409091,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000,3.272727,0.090909
Fairy,449.529412,413.176471,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235,4.117647,0.058824

In [32]:
df=pd.read_csv('/content/modified.csv')
df.head(2)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False

In [33]:
df['count']=1
df.groupby(['Type 1','Type 2']).count()['count']

Type 1  Type 2
Bug     Electric     2
        Fighting     2
        Fire         2
        Flying      14
        Ghost        1
                    ..
Water   Ice          3
        Poison       3
        Psychic      5
        Rock         4
        Steel        1
Name: count, Length: 136, dtype: int64

In [34]:
# working with large data set:
for df in pd.read_csv('/content/modified.csv', chunksize=5):
  print('CHUNK DF')
  print(df)

CHUNK DF
   #                   Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1              Bulbasaur  Grass  Poison    318  45      49       49
1  2                Ivysaur  Grass  Poison    405  60      62       63
2  3               Venusaur  Grass  Poison    525  80      82       83
3  3  VenusaurMega Venusaur  Grass  Poison    625  80     100      123
4  4             Charmander   Fire     NaN    309  39      52       43

   Sp. Atk  Sp. Def  Speed  Generation  Legendary
0       65       65     45           1      False
1       80       80     60           1      False
2      100      100     80           1      False
3      122      120     80           1      False
4       60       50     65           1      False
CHUNK DF
   #                       Name Type 1  Type 2  Total  HP  Attack  Defense  \
5  5                 Charmeleon   Fire     NaN    405  58      64       58
6  6                  Charizard   Fire  Flying    534  78      84       78
7  6  CharizardMega Charizard X   Fire  Dragon    634  78     130      111
8  6  CharizardMega Charizard Y   Fire  Flying    634  78     104       78
9  7                   Squirtle  Water     NaN    314  44      48       65

   Sp. Atk  Sp. Def  Speed  Generation  Legendary
5       80       65     80           1      False
6      109       85    100           1      False
7      130       85    100           1      False
8      159      115    100           1      False
9       50       64     43           1      False
CHUNK DF
     #                     Name Type 1  Type 2  Total  HP  Attack  Defense  \
10   8                Wartortle  Water     NaN    405  59      63       80
11   9                Blastoise  Water     NaN    530  79      83      100
12   9  BlastoiseMega Blastoise  Water     NaN    630  79     103      120
13  10                 Caterpie    Bug     NaN    195  45      30       35
14  11                  Metapod    Bug     NaN    205  50      20       55

    Sp. Atk  Sp. Def  Speed  Generation  Legendary
10       65       80     58           1      False
11       85      105     78           1      False
12      135      115     78           1      False
13       20       20     45           1      False
14       25       25     30           1      False
CHUNK DF
     #                   Name Type 1  Type 2  Total  HP  Attack  Defense  \
15  12             Butterfree    Bug  Flying    395  60      45       50
16  13                 Weedle    Bug  Poison    195  40      35       30
17  14                 Kakuna    Bug  Poison    205  45      25       50
18  15               Beedrill    Bug  Poison    395  65      90       40
19  15  BeedrillMega Beedrill    Bug  Poison    495  65     150       40

    Sp. Atk  Sp. Def  Speed  Generation  Legendary
15       90       80     70           1      False
16       20       20     50           1      False
17       25       25     35           1      False
18       45       80     75           1      False
19       15       80    145           1      False
CHUNK DF
     #                 Name  Type 1  Type 2  Total  HP  Attack  Defense  \
20  16               Pidgey  Normal  Flying    251  40      45       40
21  17            Pidgeotto  Normal  Flying    349  63      60       55
22  18              Pidgeot  Normal  Flying    479  83      80       75
23  18  PidgeotMega Pidgeot  Normal  Flying    579  83      80       80
24  19              Rattata  Normal     NaN    253  30      56       35

    Sp. Atk  Sp. Def  Speed  Generation  Legendary
20       35       35     56           1      False
21       50       50     71           1      False
22       70       70    101           1      False
23      135       80    121           1      False
24       25       35     72           1      False
CHUNK DF
     #      Name  Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  \
25  20  Raticate  Normal     NaN    413  55      81       60       50
26  21   Spearow  Normal  Flying    262  40      60       30       31
27  22    Fearow  Normal  Flying    442  65      90       65       61
28  23     Ekans  Poison     NaN    288  35      60       44       40
29  24     Arbok  Poison     NaN    438  60      85       69       65

    Sp. Def  Speed  Generation  Legendary
25       70     97           1      False
26       31     70           1      False
27       61    100           1      False
28       54     55           1      False
29       79     80           1      False
CHUNK DF
     #              Name    Type 1  Type 2  Total  HP  Attack  Defense  \
30  25           Pikachu  Electric     NaN    320  35      55       40
31  26            Raichu  Electric     NaN    485  60      90       55
32  27         Sandshrew    Ground     NaN    300  50      75       85
33  28         Sandslash    Ground     NaN    450  75     100      110
34  29  Nidoran (Female)    Poison     NaN    275  55      47       52

    Sp. Atk  Sp. Def  Speed  Generation  Legendary
30       50       50     90           1      False
31       90       80    110           1      False
32       20       30     40           1      False
33       45       55     65           1      False
34       40       40     41           1      False
CHUNK DF
     #            Name  Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  \
35  30        Nidorina  Poison     NaN    365  70      62       67       55
36  31       Nidoqueen  Poison  Ground    505  90      92       87       75
37  32  Nidoran (Male)  Poison     NaN    273  46      57       40       40
38  33        Nidorino  Poison     NaN    365  61      72       57       55
39  34        Nidoking  Poison  Ground    505  81     102       77       85

    Sp. Def  Speed  Generation  Legendary
35       55     56           1      False
36       85     76           1      False
37       40     50           1      False
38       55     65           1      False
39       75     85           1      False
CHUNK DF
     #        Name  Type 1 Type 2  Total   HP  Attack  Defense  Sp. Atk  \
40  35    Clefairy   Fairy    NaN    323   70      45       48       60
41  36    Clefable   Fairy    NaN    483   95      70       73       95
42  37      Vulpix    Fire    NaN    299   38      41       40       50
43  38   Ninetales    Fire    NaN    505   73      76       75       81
44  39  Jigglypuff  Normal  Fairy    270  115      45       20       45

    Sp. Def  Speed  Generation  Legendary
40       65     35           1      False
41       90     60           1      False
42       65     65           1      False
43      100    100           1      False
44       25     20           1      False
CHUNK DF
     #        Name  Type 1  Type 2  Total   HP  Attack  Defense  Sp. Atk  \
45  40  Wigglytuff  Normal   Fairy    435  140      70       45       85
46  41       Zubat  Poison  Flying    245   40      45       35       30
47  42      Golbat  Poison  Flying    455   75      80       70       65
48  43      Oddish   Grass  Poison    320   45      50       55       75
49  44       Gloom   Grass  Poison    395   60      65       70       85

    Sp. Def  Speed  Generation  Legendary
45       50     45           1      False
46       40     55           1      False
47       75     90           1      False
48       65     30           1      False
49       75     40           1      False
CHUNK DF
     #       Name Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  \
50  45  Vileplume  Grass  Poison    490  75      80       85      110
51  46      Paras    Bug   Grass    285  35      70       55       45
52  47   Parasect    Bug   Grass    405  60      95       80       60
53  48    Venonat    Bug  Poison    305  60      55       50       40
54  49   Venomoth    Bug  Poison    450  70      65       60       90

    Sp. Def  Speed  Generation  Legendary
50       90     50           1      False
51       55     25           1      False
52       80     30           1      False
53       55     45           1      False
54       75     90           1      False
CHUNK DF
     #     Name  Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  Sp. Def  \
55  50  Diglett  Ground     NaN    265  10      55       25       35       45
56  51  Dugtrio  Ground     NaN    405  35      80       50       50       70
57  52   Meowth  Normal     NaN    290  40      45       35       40       40
58  53  Persian  Normal     NaN    440  65      70       60       65       65
59  54  Psyduck   Water     NaN    320  50      52       48       65       50

    Speed  Generation  Legendary
55     95           1      False
56    120           1      False
57     90           1      False
58    115           1      False
59     55           1      False
CHUNK DF
     #       Name    Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  \
60  55    Golduck     Water     NaN    500  80      82       78       95
61  56     Mankey  Fighting     NaN    305  40      80       35       35
62  57   Primeape  Fighting     NaN    455  65     105       60       60
63  58  Growlithe      Fire     NaN    350  55      70       45       70
64  59   Arcanine      Fire     NaN    555  90     110       80      100

    Sp. Def  Speed  Generation  Legendary
60       80     85           1      False
61       45     70           1      False
62       70     95           1      False
63       50     60           1      False
64       80     95           1      False
CHUNK DF
     #       Name   Type 1    Type 2  Total  HP  Attack  Defense  Sp. Atk  \
65  60    Poliwag    Water       NaN    300  40      50       40       40
66  61  Poliwhirl    Water       NaN    385  65      65       65       50
67  62  Poliwrath    Water  Fighting    510  90      95       95       70
68  63       Abra  Psychic       NaN    310  25      20       15      105
69  64    Kadabra  Psychic       NaN    400  40      35       30      120

    Sp. Def  Speed  Generation  Legendary
65       40     90           1      False
66       50     90           1      False
67       90     70           1      False
68       55     90           1      False
69       70    105           1      False
CHUNK DF
     #                   Name    Type 1  Type 2  Total  HP  Attack  Defense  \
70  65               Alakazam   Psychic     NaN    500  55      50       45
71  65  AlakazamMega Alakazam   Psychic     NaN    590  55      50       65
72  66                 Machop  Fighting     NaN    305  70      80       50
73  67                Machoke  Fighting     NaN    405  80     100       70
74  68                Machamp  Fighting     NaN    505  90     130       80

    Sp. Atk  Sp. Def  Speed  Generation  Legendary
70      135       95    120           1      False
71      175       95    150           1      False
72       35       35     35           1      False
73       50       60     45           1      False
74       65       85     55           1      False
CHUNK DF
     #        Name Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  \
75  69  Bellsprout  Grass  Poison    300  50      75       35       70
76  70  Weepinbell  Grass  Poison    390  65      90       50       85
77  71  Victreebel  Grass  Poison    490  80     105       65      100
78  72   Tentacool  Water  Poison    335  40      40       35       50
79  73  Tentacruel  Water  Poison    515  80      70       65       80

    Sp. Def  Speed  Generation  Legendary
75       30     40           1      False
76       45     55           1      False
77       70     70           1      False
78      100     70           1      False
79      120    100           1      False
CHUNK DF
     #      Name Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  Sp. Def  \
80  74   Geodude   Rock  Ground    300  40      80      100       30       30
81  75  Graveler   Rock  Ground    390  55      95      115       45       45
82  76     Golem   Rock  Ground    495  80     120      130       55       65
83  77    Ponyta   Fire     NaN    410  50      85       55       65       65
84  78  Rapidash   Fire     NaN    500  65     100       70       80       80

    Speed  Generation  Legendary
80     20           1      False
81     35           1      False
82     45           1      False
83     90           1      False
84    105           1      False
CHUNK DF
     #                 Name    Type 1   Type 2  Total  HP  Attack  Defense  \
85  79             Slowpoke     Water  Psychic    315  90      65       65
86  80              Slowbro     Water  Psychic    490  95      75      110
87  80  SlowbroMega Slowbro     Water  Psychic    590  95      75      180
88  81            Magnemite  Electric    Steel    325  25      35       70
89  82             Magneton  Electric    Steel    465  50      60       95

    Sp. Atk  Sp. Def  Speed  Generation  Legendary
85       40       40     15           1      False
86      100       80     30           1      False
87      130       80     30           1      False
88       95       55     45           1      False
89      120       70     70           1      False
CHUNK DF
     #        Name  Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  \
90  83  Farfetch'd  Normal  Flying    352  52      65       55       58
91  84       Doduo  Normal  Flying    310  35      85       45       35
92  85      Dodrio  Normal  Flying    460  60     110       70       60
93  86        Seel   Water     NaN    325  65      45       55       45
94  87     Dewgong   Water     Ice    475  90      70       80       70

    Sp. Def  Speed  Generation  Legendary
90       62     60           1      False
91       35     75           1      False
92       60    100           1      False
93       70     45           1      False
94       95     70           1      False
CHUNK DF
     #      Name  Type 1  Type 2  Total   HP  Attack  Defense  Sp. Atk  \
95  88    Grimer  Poison     NaN    325   80      80       50       40
96  89       Muk  Poison     NaN    500  105     105       75       65
97  90  Shellder   Water     NaN    305   30      65      100       45
98  91  Cloyster   Water     Ice    525   50      95      180       85
99  92    Gastly   Ghost  Poison    310   30      35       30      100

    Sp. Def  Speed  Generation  Legendary
95       50     25           1      False
96      100     50           1      False
97       25     40           1      False
98       45     70           1      False
99       35     80           1      False
CHUNK DF
      #               Name   Type 1  Type 2  Total  HP  Attack  Defense  \
100  93            Haunter    Ghost  Poison    405  45      50       45
101  94             Gengar    Ghost  Poison    500  60      65       60
102  94  GengarMega Gengar    Ghost  Poison    600  60      65       80
103  95               Onix     Rock  Ground    385  35      45      160
104  96            Drowzee  Psychic     NaN    328  60      48       45

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
100      115       55     95           1      False
101      130       75    110           1      False
102      170       95    130           1      False
103       30       45     70           1      False
104       43       90     42           1      False
CHUNK DF
       #       Name    Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  \
105   97      Hypno   Psychic     NaN    483  85      73       70       73
106   98     Krabby     Water     NaN    325  30     105       90       25
107   99    Kingler     Water     NaN    475  55     130      115       50
108  100    Voltorb  Electric     NaN    330  40      30       50       55
109  101  Electrode  Electric     NaN    480  60      50       70       80

     Sp. Def  Speed  Generation  Legendary
105      115     67           1      False
106       25     50           1      False
107       50     75           1      False
108       55    100           1      False
109       80    140           1      False
CHUNK DF
       #       Name    Type 1   Type 2  Total  HP  Attack  Defense  Sp. Atk  \
110  102  Exeggcute     Grass  Psychic    325  60      40       80       60
111  103  Exeggutor     Grass  Psychic    520  95      95       85      125
112  104     Cubone    Ground      NaN    320  50      50       95       40
113  105    Marowak    Ground      NaN    425  60      80      110       50
114  106  Hitmonlee  Fighting      NaN    455  50     120       53       35

     Sp. Def  Speed  Generation  Legendary
110       45     40           1      False
111       65     55           1      False
112       50     35           1      False
113       80     45           1      False
114      110     87           1      False
CHUNK DF
       #        Name    Type 1 Type 2  Total  HP  Attack  Defense  Sp. Atk  \
115  107  Hitmonchan  Fighting    NaN    455  50     105       79       35
116  108   Lickitung    Normal    NaN    385  90      55       75       60
117  109     Koffing    Poison    NaN    340  40      65       95       60
118  110     Weezing    Poison    NaN    490  65      90      120       85
119  111     Rhyhorn    Ground   Rock    345  80      85       95       30

     Sp. Def  Speed  Generation  Legendary
115      110     76           1      False
116       75     30           1      False
117       45     35           1      False
118       70     60           1      False
119       30     25           1      False
CHUNK DF
       #                       Name  Type 1 Type 2  Total   HP  Attack  \
120  112                     Rhydon  Ground   Rock    485  105     130
121  113                    Chansey  Normal    NaN    450  250       5
122  114                    Tangela   Grass    NaN    435   65      55
123  115                 Kangaskhan  Normal    NaN    490  105      95
124  115  KangaskhanMega Kangaskhan  Normal    NaN    590  105     125

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
120      120       45       45     40           1      False
121        5       35      105     50           1      False
122      115      100       40     60           1      False
123       80       40       80     90           1      False
124      100       60      100    100           1      False
CHUNK DF
       #     Name Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  \
125  116   Horsea  Water     NaN    295  30      40       70       70
126  117   Seadra  Water     NaN    440  55      65       95       95
127  118  Goldeen  Water     NaN    320  45      67       60       35
128  119  Seaking  Water     NaN    450  80      92       65       65
129  120   Staryu  Water     NaN    340  30      45       55       70

     Sp. Def  Speed  Generation  Legendary
125       25     60           1      False
126       45     85           1      False
127       50     63           1      False
128       80     68           1      False
129       55     85           1      False
CHUNK DF
       #        Name    Type 1   Type 2  Total  HP  Attack  Defense  Sp. Atk  \
130  121     Starmie     Water  Psychic    520  60      75       85      100
131  122    Mr. Mime   Psychic    Fairy    460  40      45       65      100
132  123     Scyther       Bug   Flying    500  70     110       80       55
133  124        Jynx       Ice  Psychic    455  65      50       35      115
134  125  Electabuzz  Electric      NaN    490  65      83       57       95

     Sp. Def  Speed  Generation  Legendary
130       85    115           1      False
131      120     90           1      False
132       80    105           1      False
133       95     95           1      False
134       85    105           1      False
CHUNK DF
       #               Name  Type 1  Type 2  Total  HP  Attack  Defense  \
135  126             Magmar    Fire     NaN    495  65      95       57
136  127             Pinsir     Bug     NaN    500  65     125      100
137  127  PinsirMega Pinsir     Bug  Flying    600  65     155      120
138  128             Tauros  Normal     NaN    490  75     100       95

In [35]:
# New Project

In [45]:
df=pd.DataFrame([[1,2,3],[4,5,6],[6,7,8]],columns=['A','B','C'],index=['x','y','z'])
df

   A  B  C
x  1  2  3
y  4  5  6
z  6  7  8

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0+ bytes

In [47]:
df.describe()

              A         B         C
count  3.000000  3.000000  3.000000
mean   3.666667  4.666667  5.666667
std    2.516611  2.516611  2.516611
min    1.000000  2.000000  3.000000
25%    2.500000  3.500000  4.500000
50%    4.000000  5.000000  6.000000
75%    5.000000  6.000000  7.000000
max    6.000000  7.000000  8.000000

In [48]:
df.nunique()

A    3
B    3
C    3
dtype: int64

In [50]:
df.shape

(3, 3)

In [52]:
coffee=pd.read_csv('/content/coffee.csv')

In [53]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [ ]:
# Accessing data with pandas:

In [56]:
coffee.loc[[0,1,5]]  #[row,column]

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
5  Wednesday       Latte          25

In [61]:
coffee.loc[0:3, ['Day','Units Sold']]

       Day  Units Sold
0   Monday          25
1   Monday          15
2  Tuesday          30
3  Tuesday          20

In [65]:
coffee.iloc[0,2] # iloc doesnot include last index

np.int64(25)

In [68]:
coffee.iloc[0,0]

'Monday'

In [71]:
coffee.loc[0,'Units Sold']=10  # set the value
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          10
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [82]:
coffee.sort_values("Units Sold", ascending=False)
coffee.head(3)

       Day Coffee Type  Units Sold
0   Monday    Espresso          10
1   Monday       Latte          15
2  Tuesday    Espresso          30

In [96]:
coffee.sort_values(["Units Sold","Day"], ascending=[0,1]) # apply filter backword
coffee.head(3)

       Day Coffee Type  Units Sold
0   Monday    Espresso          10
1   Monday       Latte          15
2  Tuesday    Espresso          30

In [97]:
bios=pd.read_csv("https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/data/bios.csv")

In [100]:
bios.head(3)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17

In [110]:
bios.loc[(bios["height_cm"]>215)&(bios['born_country']=='USA')]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN

In [116]:
bios[bios['name'].str.contains("Tyson")] # apply filter for Tyson

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
4190,4204,Tyson Gray,1964-04-14,NaN,NaN,NaN,Jamaica,165.0,57.0,NaN
63488,63965,William Tyson,1971-05-17,NaN,NaN,NaN,South Africa,NaN,NaN,NaN
108751,109917,Tyson Heung,1979-05-17,Brampton,Ontario,CAN,Germany,180.0,79.0,NaN
113258,114549,Tyson Gay,1982-08-09,Lexington,Kentucky,USA,United States,181.0,80.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN
123928,126175,Tyson Williams,1989-04-01,Hamilton,Waikato,NZL,New Zealand,190.0,90.0,NaN
137426,140784,Tyson Bull,1993-05-21,Wantirna,Victoria,AUS,Australia,173.0,NaN,NaN
144324,148012,Tyson Langelaar,1999-02-17,Winnipeg,Manitoba,CAN,Canada,191.0,NaN,NaN

In [ ]:
# Q: find athleats names born in cites with that start with vowel:

In [118]:
bios[bios['born_city'].str.contains(r'^[AEIOUaeiou]',na=False)]
bios.head(3)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17

In [123]:
bios[(bios["born_country"]).isin(["USA","FRA"])&(bios['name'].str.startswith("Tyson"))]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
113258,114549,Tyson Gay,1982-08-09,Lexington,Kentucky,USA,United States,181.0,80.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN

In [126]:
bios[(bios["born_country"]).isin(["USA","FRA"])&(bios['name'].str.endswith("Burleson"))]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
77585,78176,Dyrol Burleson,1940-04-27,Saginaw,Michigan,USA,United States,187.0,72.0,NaN

In [129]:
bios.query('born_country=="USA"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145445,149168,Kristen Santos,1994-11-02,Fairfield,Connecticut,USA,United States,NaN,NaN,NaN
145446,149169,Corinne Stoddard,2001-08-15,Seattle,Washington,USA,United States,NaN,NaN,NaN
145454,149180,Anna Hoffmann,2000-03-28,Madison,Wisconsin,USA,United States,NaN,NaN,NaN
145457,149183,Alix Wilkinson,2000-08-02,Mammoth Lakes,California,USA,United States,NaN,NaN,NaN
145468,149195,Justin Abdelkader,1987-02-25,Muskegon,Michigan,USA,United States,187.0,97.0,NaN

In [133]:
bios.query('born_country=="USA","FRA"' and 'name=="Burleson"')

Empty DataFrame
Columns: [athlete_id, name, born_date, born_city, born_region, born_country, NOC, height_cm, weight_kg, died_date]
Index: []

In [134]:
# Adding & Removing column

In [137]:
coffee['Price']=4.95
coffee.head(3)

       Day Coffee Type  Units Sold  Price
0   Monday    Espresso          10   4.95
1   Monday       Latte          15   4.95
2  Tuesday    Espresso          30   4.95

In [141]:
import numpy as np

In [145]:
coffee['new_price']=np.where(coffee["Coffee Type"]=="Espresso", 3.95,5.99)
coffee.head(3)

       Day Coffee Type  Units Sold  Price  new_price
0   Monday    Espresso          10   4.95       3.95
1   Monday       Latte          15   4.95       5.99
2  Tuesday    Espresso          30   4.95       3.95

In [155]:
coffee['Price']=3.99
coffee.head(2)

      Day Coffee Type  Units Sold  new_price  Price
0  Monday    Espresso          10       3.95   3.99
1  Monday       Latte          15       5.99   3.99

In [158]:
coffee['revenue']=coffee["Units Sold"]*coffee['Price']
coffee.head(3)

       Day Coffee Type  Units Sold  new_price  Price  revenue
0   Monday    Espresso          10       3.95   3.99    39.90
1   Monday       Latte          15       5.99   3.99    59.85
2  Tuesday    Espresso          30       3.95   3.99   119.70

In [160]:
bios_new=bios.copy()

In [162]:
bios_new.head(2)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN

In [182]:
from typing_extensions import Format
bios_new['born_datetime']=pd.to_datetime(bios_new['born_date']) # convert colm to date time
bios_new.head(2)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born_datetime,born_year,born_day,born_month
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1886-12-12,1886.0,12.0,12.0
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,1969-04-01,1969.0,1.0,4.0

In [231]:
bios_new['born_datetime']=pd.to_datetime(bios_new['born_date']) # convert colm to date time
bios_new["born_year"]=bios_new['born_datetime'].dt.year
bios_new['born_month']=bios_new['born_datetime'].dt.month
bios_new.groupby([bios_new["born_year"],bios_new["born_month"]])['name'].count().reset_index().sort_values("name",ascending=False)

      born_year  born_month  name
1437     1970.0         1.0   239
1461     1972.0         1.0   229
1497     1975.0         1.0   227
1629     1986.0         1.0   227
1617     1985.0         1.0   225
...         ...         ...   ...
1877     2006.0        12.0     1
1871     2006.0         3.0     1
20       1846.0         7.0     1
21       1846.0         8.0     1
22       1846.0         9.0     1

[1885 rows x 3 columns]

In [183]:
bios_new["born_year"]=bios_new['born_datetime'].dt.year
bios_new[['name','born_year']]

                         name  born_year
0       Jean-François Blanchy     1886.0
1              Arnaud Boetsch     1969.0
2                Jean Borotra     1898.0
3             Jacques Brugnon     1895.0
4                Albert Canet     1878.0
...                       ...        ...
145495      Polina Luchnikova     2002.0
145496    Valeriya Merkusheva     1999.0
145497        Yuliya Smirnova     1998.0
145498         André Foussard     1899.0
145499          Bill Phillips     1913.0

[145500 rows x 2 columns]

In [184]:
bios_new['born_month']=bios_new['born_datetime'].dt.month
bios_new[['name','born_month']]

                         name  born_month
0       Jean-François Blanchy        12.0
1              Arnaud Boetsch         4.0
2                Jean Borotra         8.0
3             Jacques Brugnon         5.0
4                Albert Canet         4.0
...                       ...         ...
145495      Polina Luchnikova         1.0
145496    Valeriya Merkusheva         9.0
145497        Yuliya Smirnova         5.0
145498         André Foussard         5.0
145499          Bill Phillips         7.0

[145500 rows x 2 columns]

In [185]:
bios_new["born_day"]=bios_new["born_datetime"].dt.day
bios_new[["name","born_day"]]

                         name  born_day
0       Jean-François Blanchy      12.0
1              Arnaud Boetsch       1.0
2                Jean Borotra      13.0
3             Jacques Brugnon      11.0
4                Albert Canet      17.0
...                       ...       ...
145495      Polina Luchnikova      30.0
145496    Valeriya Merkusheva      20.0
145497        Yuliya Smirnova       8.0
145498         André Foussard      19.0
145499          Bill Phillips      15.0

[145500 rows x 2 columns]

In [186]:
bios_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 14 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   athlete_id     145500 non-null  int64
 1   name           145500 non-null  object
 2   born_date      143693 non-null  object
 3   born_city      110908 non-null  object
 4   born_region    110908 non-null  object
 5   born_country   110908 non-null  object
 6   NOC            145499 non-null  object
 7   height_cm      106651 non-null  float64
 8   weight_kg      102070 non-null  float64
 9   died_date      33940 non-null   object
 10  born_datetime  143693 non-null  datetime64[ns]
 11  born_year      143693 non-null  float64
 12  born_day       143693 non-null  float64
 13  born_month     143693 non-null  float64
dtypes: datetime64[ns](1), float64(5), int64(1), object(7)
memory usage: 15.5+ MB

In [187]:
# filter condition:

In [188]:
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born_datetime,born_year,born_day,born_month
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1886-12-12,1886.0,12.0,12.0
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,1969-04-01,1969.0,1.0,4.0
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,1898-08-13,1898.0,13.0,8.0
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,1895-05-11,1895.0,11.0,5.0
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,1878-04-17,1878.0,17.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,2002-01-30,2002.0,30.0,1.0
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,1999-09-20,1999.0,20.0,9.0
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,1998-05-08,1998.0,8.0,5.0
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,1899-05-19,1899.0,19.0,5.0
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,1913-07-15,1913.0,15.0,7.0

In [200]:
def categories_athlete(row):

    if row["height_cm"] < 175 and row["weight_kg"] < 70:
        return "lightweight"

    elif row["height_cm"] < 185 or row["weight_kg"] <= 80:
        return "mediumweight"

    else:
        return "heavyweight"


bios_new["category"] = bios_new.apply(categories_athlete, axis=1)

In [201]:
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born_datetime,born_year,born_day,born_month,category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1886-12-12,1886.0,12.0,12.0,heavyweight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,1969-04-01,1969.0,1.0,4.0,mediumweight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,1898-08-13,1898.0,13.0,8.0,mediumweight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,1895-05-11,1895.0,11.0,5.0,lightweight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,1878-04-17,1878.0,17.0,4.0,heavyweight

In [202]:
# Merging and cocnating data:

In [205]:
nocs=pd.read_csv("/content/noc_regions.csv")
nocs.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [207]:
usa=bios_new[bios_new["born_country"]=="USA"].copy()
ugb=bios_new[bios_new["born_country"]=="GBR"].copy()

In [211]:
new_df=pd.concat([usa,ugb])
new_df

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born_datetime,born_year,born_day,born_month,category
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN,1967-07-22,1967.0,22.0,7.0,mediumweight
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN,1968-09-17,1968.0,17.0,9.0,lightweight
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN,1973-10-03,1973.0,3.0,10.0,lightweight
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20,1897-07-01,1897.0,1.0,7.0,heavyweight
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN,1975-01-06,1975.0,6.0,1.0,lightweight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144811,148512,Benjamin Alexander,1983-05-08,London,England,GBR,Jamaica,NaN,NaN,NaN,1983-05-08,1983.0,8.0,5.0,heavyweight
144815,148517,Ashley Watson,1993-10-28,Peterborough,England,GBR,Jamaica,NaN,NaN,NaN,1993-10-28,1993.0,28.0,10.0,heavyweight
145005,148716,Peder Kongshaug,2001-08-13,Wimbledon,England,GBR,Norway,184.0,86.0,NaN,2001-08-13,2001.0,13.0,8.0,mediumweight
145319,149041,Axel Brown,1992-04-02,Harrogate,England,GBR,Trinidad and Tobago,NaN,NaN,NaN,1992-04-02,1992.0,2.0,4.0,heavyweight
145388,149111,Jean-Luc Baker,1993-10-07,Burnley,England,GBR,United States,NaN,NaN,NaN,1993-10-07,1993.0,7.0,10.0,heavyweight

In [212]:
result=pd.read_csv("/content/results.csv")

In [214]:
combined_col=pd.merge(result,bios_new, on="athlete_id",how="left")

In [215]:
combined_col

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,...,born_country,NOC,height_cm,weight_kg,died_date,born_datetime,born_year,born_day,born_month,category
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,...,FRA,France,NaN,NaN,1960-10-02,1886-12-12,1886.0,12.0,12.0,heavyweight
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,...,FRA,France,NaN,NaN,1960-10-02,1886-12-12,1886.0,12.0,12.0,heavyweight
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,...,FRA,France,NaN,NaN,1960-10-02,1886-12-12,1886.0,12.0,12.0,heavyweight
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,...,FRA,France,NaN,NaN,1960-10-02,1886-12-12,1886.0,12.0,12.0,heavyweight
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,...,FRA,France,NaN,NaN,1960-10-02,1886-12-12,1886.0,12.0,12.0,heavyweight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,...,SVK,Slovakia,196.0,108.0,NaN,2001-07-12,2001.0,12.0,7.0,heavyweight
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,...,SWE,Sweden,NaN,NaN,NaN,1998-03-28,1998.0,28.0,3.0,heavyweight
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,...,SWE,Sweden,NaN,NaN,NaN,2000-08-16,2000.0,16.0,8.0,heavyweight
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,...,SWE,Sweden,NaN,NaN,NaN,2000-08-16,2000.0,16.0,8.0,heavyweight
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,...,SWE,Sweden,NaN,NaN,NaN,1994-10-07,1994.0,7.0,10.0,heavyweight

In [ ]:
# Handling null values:

In [217]:
coffee.head(3)

       Day Coffee Type  Units Sold  new_price  Price  revenue
0   Monday    Espresso          10       3.95   3.99    39.90
1   Monday       Latte          15       5.99   3.99    59.85
2  Tuesday    Espresso          30       3.95   3.99   119.70

In [218]:
coffee.loc[0:1,"Units Sold"]=np.nan  # making null values

In [219]:
coffee.head(3)

       Day Coffee Type  Units Sold  new_price  Price  revenue
0   Monday    Espresso         NaN       3.95   3.99    39.90
1   Monday       Latte         NaN       5.99   3.99    59.85
2  Tuesday    Espresso        30.0       3.95   3.99   119.70

In [220]:
coffee.isna().sum()

Day            0
Coffee Type    0
Units Sold     2
new_price      0
Price          0
revenue        0
dtype: int64

In [221]:
coffee.fillna(coffee["Units Sold"].mean())

          Day Coffee Type  Units Sold  new_price  Price  revenue
0      Monday    Espresso        35.0       3.95   3.99    39.90
1      Monday       Latte        35.0       5.99   3.99    59.85
2     Tuesday    Espresso        30.0       3.95   3.99   119.70
3     Tuesday       Latte        20.0       5.99   3.99    79.80
4   Wednesday    Espresso        35.0       3.95   3.99   139.65
5   Wednesday       Latte        25.0       5.99   3.99    99.75
6    Thursday    Espresso        40.0       3.95   3.99   159.60
7    Thursday       Latte        30.0       5.99   3.99   119.70
8      Friday    Espresso        45.0       3.95   3.99   179.55
9      Friday       Latte        35.0       5.99   3.99   139.65
10   Saturday    Espresso        45.0       3.95   3.99   179.55
11   Saturday       Latte        35.0       5.99   3.99   139.65
12     Sunday    Espresso        45.0       3.95   3.99   179.55
13     Sunday       Latte        35.0       5.99   3.99   139.65

In [223]:
bios_new.head(3)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born_datetime,born_year,born_day,born_month,category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1886-12-12,1886.0,12.0,12.0,heavyweight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,1969-04-01,1969.0,1.0,4.0,mediumweight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,1898-08-13,1898.0,13.0,8.0,mediumweight

In [224]:
bios_new["born_city"].value_counts()

born_city
Budapest           1378
Moskva (Moscow)     883
Oslo                708
Stockholm           629
Praha (Prague)      600
                   ...
Kirovgrad             1
Pereiaslav            1
Podgornyy             1
Kudepsta              1
Furmanov              1
Name: count, Length: 22368, dtype: int64

In [ ]:
#Aggregating data:

In [225]:
bios_new[bios_new["born_country"]=="USA"]["born_region"].value_counts() # how many are from USA and count their region

born_region
California              1634
New York                 990
Illinois                 585
Massachusetts            530
Pennsylvania             530
New Jersey               381
Texas                    368
Minnesota                365
Ohio                     328
Michigan                 319
Washington               240
Florida                  235
Wisconsin                209
Colorado                 207
Connecticut              156
Indiana                  150
Oregon                   132
Georgia                  129
Virginia                 121
Maryland                 117
District of Columbia     107
Iowa                     102
Hawaiʻi                   95
Kansas                    94
Oklahoma                  93
Louisiana                 92
Utah                      91
Missouri                  91
North Carolina            86
Arizona                   83
New Hampshire             83
Vermont                   68
Mississippi               66
Alabama                   64
Kentucky                  62
Tennessee                 62
Nebraska                  60
Rhode Island              56
Montana                   55
Maine                     50
South Carolina            50
Alaska                    45
Arkansas                  42
Idaho                     41
New Mexico                38
Nevada                    36
South Dakota              27
West Virginia             24
Delaware                  22
North Dakota              16
Wyoming                   14
Name: count, dtype: int64

In [227]:
coffee.groupby(["Coffee Type"])["Units Sold"].sum()

Coffee Type
Espresso    240.0
Latte       180.0
Name: Units Sold, dtype: float64

In [228]:
coffee.groupby(["Coffee Type"]).agg({"Units Sold":'sum',"Price":'mean'})

             Units Sold  Price
Coffee Type
Espresso          240.0   3.99
Latte             180.0   3.99

In [230]:
pivot=coffee.pivot(columns="Coffee Type",index="Day",values="revenue")
pivot

Coffee Type  Espresso   Latte
Day
Friday         179.55  139.65
Monday          39.90   59.85
Saturday       179.55  139.65
Sunday         179.55  139.65
Thursday       159.60  119.70
Tuesday        119.70   79.80
Wednesday      139.65   99.75

In [233]:
bios_new.head(3)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born_datetime,born_year,born_day,born_month,category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1886-12-12,1886.0,12.0,12.0,heavyweight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,1969-04-01,1969.0,1.0,4.0,mediumweight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,1898-08-13,1898.0,13.0,8.0,mediumweight

In [237]:
bios_new["height_ranked"]=bios_new["height_cm"].rank(ascending=False)
bios_new.sort_values(["height_ranked"])

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born_datetime,born_year,born_day,born_month,category,height_ranked
89070,89782,Yao Ming,1980-09-12,Xuhui District,Shanghai,CHN,People's Republic of China,226.0,141.0,NaN,1980-09-12,1980.0,12.0,9.0,heavyweight,1.0
6978,7013,Arvydas Sabonis,1964-12-19,Kaunas,Kaunas,LTU,Lithuania Soviet Union,223.0,122.0,NaN,1964-12-19,1964.0,19.0,12.0,heavyweight,2.5
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN,1952-02-24,1952.0,24.0,2.0,heavyweight,2.5
5673,5696,Gunther Behnke,1963-01-19,Leverkusen,Nordrhein-Westfalen,GER,Germany,221.0,114.0,NaN,1963-01-19,1963.0,19.0,1.0,heavyweight,5.0
89075,89787,Roberto Dueñas,1975-11-01,Madrid,Madrid,ESP,Spain,221.0,137.0,NaN,1975-11-01,1975.0,1.0,11.0,heavyweight,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145490,149217,Sin Ye-Chan,1995-06-13,NaN,NaN,NaN,Republic of Korea,NaN,NaN,NaN,1995-06-13,1995.0,13.0,6.0,heavyweight,NaN
145491,149218,Matthew Wepke,1989-12-05,NaN,NaN,NaN,Jamaica,NaN,NaN,NaN,1989-12-05,1989.0,5.0,12.0,heavyweight,NaN
145492,149219,Carlos García-Ordóñez,1927-04-24,La Habana (Havana),Ciudad de La Habana,CUB,Cuba,NaN,NaN,2019-11-24,1927-04-24,1927.0,24.0,4.0,heavyweight,NaN
145493,149220,Landysh Falyakhova,1998-08-31,Dva Polya Artash,Respublika Tatarstan,RUS,ROC,NaN,NaN,NaN,1998-08-31,1998.0,31.0,8.0,heavyweight,NaN
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,1913-07-15,1913.0,15.0,7.0,heavyweight,NaN

In [239]:
!git clone https://github.com/sabanoureen/pandas-data-analysis.git

Cloning into 'pandas-data-analysis'...
warning: You appear to have cloned an empty repository.

In [247]:
%cd pandas-data-analysis

[Errno 2] No such file or directory: 'pandas-data-analysis'
/content/pandas-data-analysis

In [248]:
!mkdir data

In [249]:
!cp /content/*.csv data/

In [250]:
!ls data

coffee.csv	 modified.csv	  pokemon_data.csv
data_filter.csv  noc_regions.csv  results.csv